### ISSUE TITLE
Couldn't build on Ubuntu 19.10

### ISSUE THREAD

**Issue by Mitsunee** [SubhadeepJasu/pebbles#67]
or rather install? I'm not sure, the last command I issued was `sudo ninja install` after I made sure I have all of the depencies and done a build on a fresh local clone.

![Screenshot_20200810_180729](https://user-images.githubusercontent.com/19474909/89804951-280e5900-db35-11ea-9dff-283aa23b13d7.png)

**Comment by daniel071** [comment]
Can confirm, I'm having the same issue on Arch Linux
```
$ sudo ninja install
[6/56] Compiling Vala source ../src/Application.vala ../src/Settings.vala ../src/MainWindow.v....vala ../src/Views/Displays/StatisticsDisplay.vala ../src/Views/Displays/StatisticsGraph.vala
FAILED: com.github.subhadeepjasu.pebbles@exe/src/Application.c com.github.subhadeepjasu.pebbles@exe/src/Settings.c com.github.subhadeepjasu.pebbles@exe/src/MainWindow.c com.github.subhadeepjasu.pebbles@exe/src/StyledButton.c com.github.subhadeepjasu.pebbles@exe/src/KeyboardHandler.c com.github.subhadeepjasu.pebbles@exe/src/ControlsScheme.c com.github.subhadeepjasu.pebbles@exe/src/PreferencesOverlay.c com.github.subhadeepjasu.pebbles@exe/src/Test/TestUtil.c com.github.subhadeepjasu.pebbles@exe/src/Core/EvaluationResult.c com.github.subhadeepjasu.pebbles@exe/src/Core/HistoryManager.c com.github.subhadeepjasu.pebbles@exe/src/Core/ScientificCalculator.c com.github.subhadeepjasu.pebbles@exe/src/Core/Calculus.c com.github.subhadeepjasu.pebbles@exe/src/Core/ProgrammerCalculator.c com.github.subhadeepjasu.pebbles@exe/src/Core/Statistics.c com.github.subhadeepjasu.pebbles@exe/src/Core/Utils.c com.github.subhadeepjasu.pebbles@exe/src/Core/Converter.c com.github.subhadeepjasu.pebbles@exe/src/Core/CurrencyConverter.c com.github.subhadeepjasu.pebbles@exe/src/Core/DateCalculator.c com.github.subhadeepjasu.pebbles@exe/src/Views/MiniCalculator.c com.github.subhadeepjasu.pebbles@exe/src/Views/CalculusView.c com.github.subhadeepjasu.pebbles@exe/src/Views/ProgrammerView.c com.github.subhadeepjasu.pebbles@exe/src/Views/ScientificView.c com.github.subhadeepjasu.pebbles@exe/src/Views/DateView.c com.github.subhadeepjasu.pebbles@exe/src/Views/StatisticsView.c com.github.subhadeepjasu.pebbles@exe/src/Views/CommonNumericKeypad.c com.github.subhadeepjasu.pebbles@exe/src/Views/CommonKeyPadConverter.c com.github.subhadeepjasu.pebbles@exe/src/Views/ConvLengthView.c com.github.subhadeepjasu.pebbles@exe/src/Views/ConvAreaView.c com.github.subhadeepjasu.pebbles@exe/src/Views/ConvVolumeView.c com.github.subhadeepjasu.pebbles@exe/src/Views/ConvTimeView.c com.github.subhadeepjasu.pebbles@exe/src/Views/ConvAngleView.c com.github.subhadeepjasu.pebbles@exe/src/Views/ConvSpeedView.c com.github.subhadeepjasu.pebbles@exe/src/Views/ConvPressView.c com.github.subhadeepjasu.pebbles@exe/src/Views/ConvMassView.c com.github.subhadeepjasu.pebbles@exe/src/Views/ConvEnergyView.c com.github.subhadeepjasu.pebbles@exe/src/Views/ConvPowerView.c com.github.subhadeepjasu.pebbles@exe/src/Views/ConvTempView.c com.github.subhadeepjasu.pebbles@exe/src/Views/ConvDataView.c com.github.subhadeepjasu.pebbles@exe/src/Views/ConvCurrView.c com.github.subhadeepjasu.pebbles@exe/src/Views/BitToggleGrid.c com.github.subhadeepjasu.pebbles@exe/src/Views/ControlsOverlay.c com.github.subhadeepjasu.pebbles@exe/src/Views/HistoryView.c com.github.subhadeepjasu.pebbles@exe/src/Views/BottomPopper.c com.github.subhadeepjasu.pebbles@exe/src/Views/Displays/ScientificDisplay.c com.github.subhadeepjasu.pebbles@exe/src/Views/Displays/CalculusDisplay.c com.github.subhadeepjasu.pebbles@exe/src/Views/Displays/ProgrammerDisplay.c com.github.subhadeepjasu.pebbles@exe/src/Views/Displays/StatisticsDisplay.c com.github.subhadeepjasu.pebbles@exe/src/Views/Displays/StatisticsGraph.c 
valac -C --debug --debug --pkg posix --pkg posix --pkg json-glib-1.0 --pkg libsoup-2.4 --pkg gobject-2.0 --pkg gsl --pkg glib-2.0 --pkg gtk+-3.0 --pkg granite --color=always --directory com.github.subhadeepjasu.pebbles@exe --basedir ../ --gresources=../data/com.github.subhadeepjasu.pebbles.gresource.xml ../src/Application.vala ../src/Settings.vala ../src/MainWindow.vala ../src/StyledButton.vala ../src/KeyboardHandler.vala ../src/ControlsScheme.vala ../src/PreferencesOverlay.vala ../src/Test/TestUtil.vala ../src/Core/EvaluationResult.vala ../src/Core/HistoryManager.vala ../src/Core/ScientificCalculator.vala ../src/Core/Calculus.vala ../src/Core/ProgrammerCalculator.vala ../src/Core/Statistics.vala ../src/Core/Utils.vala ../src/Core/Converter.vala ../src/Core/CurrencyConverter.vala ../src/Core/DateCalculator.vala ../src/Views/MiniCalculator.vala ../src/Views/CalculusView.vala ../src/Views/ProgrammerView.vala ../src/Views/ScientificView.vala ../src/Views/DateView.vala ../src/Views/StatisticsView.vala ../src/Views/CommonNumericKeypad.vala ../src/Views/CommonKeyPadConverter.vala ../src/Views/ConvLengthView.vala ../src/Views/ConvAreaView.vala ../src/Views/ConvVolumeView.vala ../src/Views/ConvTimeView.vala ../src/Views/ConvAngleView.vala ../src/Views/ConvSpeedView.vala ../src/Views/ConvPressView.vala ../src/Views/ConvMassView.vala ../src/Views/ConvEnergyView.vala ../src/Views/ConvPowerView.vala ../src/Views/ConvTempView.vala ../src/Views/ConvDataView.vala ../src/Views/ConvCurrView.vala ../src/Views/BitToggleGrid.vala ../src/Views/ControlsOverlay.vala ../src/Views/HistoryView.vala ../src/Views/BottomPopper.vala ../src/Views/Displays/ScientificDisplay.vala ../src/Views/Displays/CalculusDisplay.vala ../src/Views/Displays/ProgrammerDisplay.vala ../src/Views/Displays/StatisticsDisplay.vala ../src/Views/Displays/StatisticsGraph.vala
../src/Core/CurrencyConverter.vala:128.13-128.23: warning: `null' incompatible with return type `double[]'
            return null;
            ^^^^^^^^^^^
../src/MainWindow.vala:749.48-749.74: error: The name `QWD' does not exist in the context of `Pebbles.GlobalAngleUnit'
            if (settings.global_word_length == Pebbles.GlobalAngleUnit.QWD) {
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/MainWindow.vala:755.53-755.79: error: The name `DWD' does not exist in the context of `Pebbles.GlobalAngleUnit'
            else if (settings.global_word_length == Pebbles.GlobalAngleUnit.DWD) {
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/MainWindow.vala:761.53-761.79: error: The name `WRD' does not exist in the context of `Pebbles.GlobalAngleUnit'
            else if (settings.global_word_length == Pebbles.GlobalAngleUnit.WRD) {
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/MainWindow.vala:767.53-767.79: error: The name `BYT' does not exist in the context of `Pebbles.GlobalAngleUnit'
            else if (settings.global_word_length == Pebbles.GlobalAngleUnit.BYT) {
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
Compilation failed: 4 error(s), 1 warning(s)
ninja: build stopped: subcommand failed.

```

**Comment by Mitsunee** [comment]
interestingly you get a few less errors, so I'm guessing the version of granite I'm getting from the ubuntu repo is too outdated. No clue where the other 4 errors are coming from tho.

**Comment by SubhadeepJasu** [comment]
@Mitsunee The other 4 errors should be gone now. See #65 . The granite error could be a version mismatch.

**Comment by daniel071** [comment]
I see, I switched to the `programmer_mode` branch and the issue was fixed.

@Mitsunee Try this:
```shell
git pull origin programmer_mode
git checkout programmer_mode

meson --reconfigure build/
meson build --prefix=/usr

cd build
sudo ninja install
com.github.subhadeepjasu.pebbles
```

**Comment by SubhadeepJasu** [comment]
I just updated master a while back. In programmer_mode branch the input may be a bit wonky. Let me know if something like that still happens, because on my local build, meson didn't warn me about the error which is weird.

**Comment by Mitsunee** [comment]
the granite errors were a version missmatch, I managed to find the packages in question in aptitude and they're older than 5.3, so if the other errors are solved, this Issue here can be closed

**Comment by Mitsunee** [comment]
Tried to build again on Ubuntu 20.04LTS and now everything works. Finally got to replace KCalc :)

**Comment by SubhadeepJasu** [comment]
Glad to know. 🎊🎉
